MERL-8: Add ability to reuse recent image as inline build cache

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -13,42 +13,69 @@ stages:
 
 include:
   - project: "ska-telescope/templates-repository"
-    file: 
-     - "gitlab-ci/includes/python.gitlab-ci.yml"
-     - "gitlab-ci/includes/docs.gitlab-ci.yml"
-     - "gitlab-ci/includes/finaliser.gitlab-ci.yml"
-     - "gitlab-ci/includes/release.gitlab-ci.yml"
+    file:
+      - "gitlab-ci/includes/python.gitlab-ci.yml"
+      - "gitlab-ci/includes/docs.gitlab-ci.yml"
+      - "gitlab-ci/includes/finaliser.gitlab-ci.yml"
+      - "gitlab-ci/includes/release.gitlab-ci.yml"
 
-version-docker:
+build-docker:
   stage: build
+  image: docker:latest
+  services:
+    - docker:dind # docker-in-docker service
+  before_script:
+    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
   script:
+    # Find commit SHA to build
     - git fetch --unshallow
-    - echo DOCKER_IMAGE = ${CI_REGISTRY_IMAGE}:$(git log -n 1 --pretty=format:%H -- Dockerfile) > versions.env
+    - COMMIT_SHA=$(git log -n 1 --pretty=format:%H -- Dockerfile)
+    - |
+      if [[ -z $COMMIT_SHA ]]; then
+        echo "ERROR: No commit SHA found for Dockerfile"
+        exit 1
+      fi
+    - DOCKER_IMAGE=$CI_REGISTRY_IMAGE:$COMMIT_SHA
+    - echo "DOCKER_IMAGE=$DOCKER_IMAGE" > versions.env
+    - cat versions.env
 
+    # Skip build if adequate image already in registry
+    - |
+      if docker manifest inspect $DOCKER_IMAGE > /dev/null 2>&1; then
+        echo "Up-to-date image already in registry for commit $COMMIT_SHA"
+        echo "BUILD_CACHE_IMAGE=$DOCKER_IMAGE" > build_cache_image.env
+        exit 0
+      fi
+
+    # Build
+    - |
+      if [[ -f build_cache_image.env ]]; then
+        source build_cache_image.env
+      fi
+    - |
+      if [[ -z $BUILD_CACHE_IMAGE ]]; then
+        echo "Building Dockerfile at commit $COMMIT_SHA without build cache"
+        docker build . --build-arg BUILDKIT_INLINE_CACHE=1 --tag $DOCKER_IMAGE
+      else
+        echo "Building Dockerfile at commit $COMMIT_SHA using build cache from: $BUILD_CACHE_IMAGE"
+        docker build . --build-arg BUILDKIT_INLINE_CACHE=1 --tag $DOCKER_IMAGE --cache-from $BUILD_CACHE_IMAGE
+      fi
+    - docker push $DOCKER_IMAGE
+    - echo "BUILD_CACHE_IMAGE=$DOCKER_IMAGE" > build_cache_image.env
+
+  # Make image name available to dependent jobs
   artifacts:
     reports:
       dotenv: versions.env
 
-build-docker:
-  stage: build
-  needs:
-    - job: version-docker
-      artifacts: true
-  image: docker:latest
-  services:
-    - docker:dind  # docker-in-docker service
-  before_script:
-    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
-  script:
-    - |
-      if ! docker manifest inspect $DOCKER_IMAGE > /dev/null; then
-        docker build --build-arg BUILDKIT_INLINE_CACHE=1 --tag $DOCKER_IMAGE .
-        docker push $DOCKER_IMAGE
-      fi
+  # Cache the most recent image name available in registry, on a per-branch basis
+  cache:
+    key: $CI_COMMIT_REF_NAME
+    fallback_keys:
+      - $CI_DEFAULT_BRANCH
+    paths:
+      - build_cache_image.env
 
 python-test:
-  needs:
-    - job: version-docker
-      artifacts: true
-    - job: build-docker
+  needs: ["build-docker"]
   image: $DOCKER_IMAGE
